# Lesson 9

This notebook will cover the follwoing topics:

1. Numpy shallow and deep copies
2. Panda series
3. Dataframes contruction and creation 
4. Pandas file reading and statistics basics
5. Pandas project


## 9.1 Numpy shallow and deep copies (Follow)

**Learning Objectives:**
1. Understand the difference between shallow and deep copies.
2. Understand when it is appropriate to use shallow and deep copies.

In [6]:
# add comments to the code

import numpy as np

numbers = np.arange(1, 6)
numbers2 = numbers.view()

print(id(numbers))
print(id(numbers2), '\n')

numbers *= 10

print(numbers, '\n')
print(numbers2, '\n')

numbers2 += 10

print(numbers, '\n')
print(numbers2, '\n')


numbers3 = np.arange(1, 6)
numbers4 = numbers3.copy()

print(numbers3, '\n')
print(numbers4, '\n')

numbers3 *= 5

print(numbers3, '\n')
print(numbers4, '\n')



2356047850832
2356048189264 

[10 20 30 40 50] 

[10 20 30 40 50] 

[20 30 40 50 60] 

[20 30 40 50 60] 

[1 2 3 4 5] 

[1 2 3 4 5] 

[ 5 10 15 20 25] 

[1 2 3 4 5] 



### As the above code executes, think about the following questions:

1. What is the difference between a shallow and deep copy?
2. What would be a situation where a shallow copy would be prefered?
3. What woudl be a situation where a deep copy would be preferred?

## 9.1 Numpy shallow and deep copies (Group)

**Write a program that will do the following:**
1. Create a tree of numpy arrays.
2. The tree should have at least 5 numpy arrays.
3. The tree should be a binary tree.
4. Each node of the tree should be generated from the parent. 
5. The child should be 2 times the values for the parent.
6. For example: if parent node = ([1, 2, 3]), the child should be = ([2, 4, 6])
7. Gather the arrays in a list and traverse them in the method of your choosing.
8. Print the results to the screen.
9. Try to use deep and/or shallow copies to accomplish this task.
10. Try to do this in an iterative fashion.


In [4]:
import numpy as np
import networkx as nx

graph = nx.Graph()

g.add_edge(1,2)
g.add_edge(1,3)
g.add_edge(2,4)
g.add_edge(2,5)
g.add_edge(3,6)
g.add_edge(3,7)

g.nodes[1]["parent"]=np.nan
g.nodes[2]["parent"]=1
g.nodes[3]["parent"]=1
g.nodes[4]["parent"]=2
g.nodes[5]["parent"]=2
g.nodes[6]["parent"]=3
g.nodes[7]["parent"]=3


In [ ]:
import numpy as np
from networkx.drawing.nx_pydot import graphviz_layout
import networkx as nx

g = nx.Graph()

g.add_edge(1,2)
g.add_edge(1,3)
g.add_edge(2,4)
g.add_edge(2,5)
g.add_edge(3,6)
g.add_edge(3,7)

g.nodes[1]["parent"]=np.nan
g.nodes[2]["parent"]=1
g.nodes[3]["parent"]=1
g.nodes[4]["parent"]=2
g.nodes[5]["parent"]=2
g.nodes[6]["parent"]=3
g.nodes[7]["parent"]=3

g.nodes[1]["value"]=np.array([1,2,3])

value = nx.get_node_attributes(g, "value")
parent = nx.get_node_attributes(g, "parent")
print("parent attribute {node:value}:",parent,"\n")
print("value attribute {node:value} :",value)

for x in range(2, len(parent)+1):
    g.nodes[x]["value"]=value[parent[x]]*2
    value = nx.get_node_attributes(g, "value")
    print("value attribute {node:value} :",value)

###########
# Convert value, which is a 
###########
# Convert value, which is a dictionary of nodes and 
# the list stored as the value attribute for that node
# into two lists to fulfill the stated requirements
# then print them
###########
    
Nodes = list(value.keys())
Values = list(value.values())

print("\nNode\t","Value")

for i in range(len(Nodes)):
    print(Nodes[i],"\t",Values[i])

#for key, value in value.items():
#    print(key,"\t", value)
    
#[print(key,'\t', value) for key, value in value.items()]
    
#for key in value:
#    print(key,"\t", value[key])


pos = graphviz_layout(g, prog="dot")
node_labels = nx.get_node_attributes(g,'value')
nx.draw(g, pos, node_color = 'w', edge_color = 'g', with_labels = True, labels = node_labels)


## 9.2 Panda Series (Follow)

**Learning Objectives:**
1. Understand how to manipulate and create panda series.
2. Understand how panda series are different from numpy arrays.

In [14]:
# add comments to the code

import pandas as pd

# grades = pd.Series([87, 100, 94])
# print(grades)
# print(grades[0])

# print(grades.count(), '\n')
# print(grades.mean(), '\n')
# print(grades.min(), '\n')
# print(grades.max(), '\n')
# print(grades.describe(), '\n')
# print(grades.describe()[0], '\n')

grades = pd.Series([87, 100, 94], index = ['Wally', 'Eva', 'Sam'])
print(grades, '\n')
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})

print(grades['Eva'], '\n')
print(grades.Wally, '\n')

Wally     87
Eva      100
Sam       94
dtype: int64 

100 

87 



### As the above code executes, think about the following questions:

1. How is a pandas series different/same as a numpy array?
2. What do the .count(), .mean(), ... functions do?
3. What is meant by pandas supports custom indexing?

## 9.2 Panda Series (Group)

**Write a program that will do the following:**
1. Create a NUMPY array of random integers.  
2. The array should have at least 10 elements.
3. Convert the array to a panda series.
4. Produce descriptive statistics for the series.
5. As an added challenge, try to make the numpy array always return the same values.

In [16]:
import numpy as np
import pandas as pd

random_np = np.random.randint(1,101,5)
pd_array = pd.Series(random_np)

print(pd_array.describe(), '\n')

count     5.000000
mean     18.400000
std       9.813256
min       5.000000
25%      16.000000
50%      17.000000
75%      22.000000
max      32.000000
dtype: float64 



## 9.3 Dataframes construction and creation (Follow)

**Learning Objectives:**
1. Understand how dataframes are created.
2. Understand how dataframes are used.
3. Understand how to manipulate dataframes.

In [ ]:
import pandas as pd

grades_dict = {'Wally': [87, 96, 70, 90], 'Eva': [100, 87, 90, 92], 
               'Sam': [94, 77, 90, 89], 'Katie': [100, 81, 82, 85],
               'Bob': [83, 65, 85, 78]}

grades = pd.DataFrame(grades_dict)
print(grades, '\n')
grades.index = ['Test1', 'Test2', 'Test3', 'Test4']
print(grades, '\n')
print(grades['Eva'], '\n')

print(grades.loc['Test1'], '\n')
print(grades.iloc[1], '\n')

print(grades.loc['Test1': 'Test3'])

### As the above code executes, think about the following questions:

1. What is a dataframe and how is it different/same from a series or numpy array?
2. What does the loc function do?
3. What does the iloc function do?


## 9.3 Dataframes construction and creation (Group)

**Write a program that will do the following:**
1. Create a dataframe with employees, job title, salary, and years worked.
2. There should be at least 5 entries.
3. Add indexes to the rows so when you print the dataframe it will display properly.
4. Try writing commands using iloc and loc to extract different rows and columns from the dataframe.
5. You may be asked to share things you did.


## 9.4 Pandas file reading and statistics basics (Follow)

**Learning Objectives:**
1. Understand what statistics can be easily found using pandas.
2. Understand how those statistics can be used.

In [ ]:
# Add comments to the code

import pandas as pd

df = pd.read_csv('data/raisin_dataset.csv')

print(df)
#print(df['Area']) 

df2 = df['Area']
#print(df2)

df.drop('Area', inplace=True, axis=1)
#print(df)

#print(df['MinorAxisLength'].mean())

#print(df[df['Class'] == 'Besni'])


### As the above code executes, think about the following questions:

1. What does df['Area'] do?
2. What does the inplace=True do in line 13?
3. What does line 18 do?

## 9.4 Pandas file reading and statistics basics (Group)

**Write a porgram that will do the following:**
1. Take the raisins dateset and break it into 2 datasets by class label.
2. One dataset should be the Kecimen class and the second should be the Besni class.
3. Find the mean of each column in the two new datasets.
4. Find the standard deviation for each column of the dataset.
5. Which column best predicts the class label?


## 9.5 Pandas project (Group)

**Write a program that will do the following:**
1. Read in the team summaries datset included.  
2. Do some basic statistical analysis.  
3. Try to create an argument to determine the best NBA team of all time.  
4. You may also use a different dataset and do a different analysis. 
5. Use the pandas library in your project.

In [ ]:
# Below is the website for the NBA dataset
# https://www.kaggle.com/sumitrodatta/nba-aba-baa-stats

